language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: trusty
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: mAKXFRm0NrCBeNZjgIThS74crkpc9PZvXuhxZJRBwNNfLEDG9eTCpx7l+onQ1ruHwDxpzCQjRa68Zx9bWekpK7KbQ9kECSJ4aepfyfkJ+8dt+q3V80sOripslCc0OSVwkNlhnJsK1+Bg6Pi37CzgK+OoOK978xD4mglLIiTLHbNAnr7WxvO9u0C5Jcx232N4PG0x3OwoR2wd9wcu54J77FxoOcTw5ZX8E/iFo8oFttEppAJU2NwldPmcNxjcGYBU9wgAbQhueylkyn43Db0GusQ4lBLRC5VC8Ksoh0s+g/OOHWuWjE6DSBBJe13uICOX9nsQmFuoB8OYvoS7ueH3iXtWkN/5IFx+7DZ7zVc8L4vsx/86ZyoeFySzmzLA4MB0Un5ROA0OtXPSeE2md8ngIHYUuX3XQLmA30UyGMd3lk0/7z9h4kHpp7pDkvH7uAyLIsVvhFT77Z3Wjfsb0V2HNhDgRX4mN27Z0MR3avSlKZMq6BYbCNxGXwS0iQgneFl8NgiFYDKLRUqpbe4D95u+8d9UOEXYB0jv2CkFfE5AdBqWufbb3zp4RmLlLXMQ/uKUO3/djykldNpaHmjGbYxhJkGPoIX33PGIQBhYHPwTPavnCp0GTSejvHNg8ecAFYf/Z5cn/LCz5nBmK79M2TzyG8Ht/L9MXX+BGcoPaC+qVyc=
  app: https://brownsfield.herokuapp.com/
  run: rails db:migrate
