# Add configuration values here, as shown below.
#
YOUTUBE_API_KEY: AIzaSyDyY__HGUskUuI_HVQg2wOVpJZZBiEoDKU
GH_API_KEY: token 7ba523bc8ab3171fc0964d99d0b14521e724e863

#notes
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
# GH_API_KEY: token 49475bf778cbfec543a25d65e0bf5ed5f54ed18e
